version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    day: friday
    timezone: Africa/Cairo
  open-pull-requests-limit: 10
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    day: friday
    timezone: Africa/Cairo
  open-pull-requests-limit: 10
